Repository cognovi-ai/the-cdj-ui, pull requests merged in 2024-09, with the labels that each got.

#2 Initial atomic components.
  .babelrc
  jest.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/next.svg
  public/vercel.svg
  src/components/atoms/Text.tsx
  src/types/Text.types.d.ts
  tests/components/atoms/Text.test.tsx
  tests/jest.setup.cjs
  tsconfig.json
Labels: components, feature, minor

#3 build: add Node.js CI workflow
  .github/workflows/node.js.yml
  src/app/layout.tsx
  src/app/page.tsx
Labels: ci

#7 build: containerize the-cdj-ui dev env
  .dockerignore
  Dockerfile
  compose.yml
  package-lock.json
  package.json
Labels: enhancement, build, env, dev

#4 feat!: add button atomic component
  src/components/atoms/Button.tsx
  src/types/Button.types.d.ts
  tests/components/atoms/Button.test.tsx
Labels: enhancement, components, feature

#10 style: update eslint
  .babelrc
  .eslintrc.json
  .prettierrc
  compose.yml
  jest.config.js
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/Text.tsx
  src/types/Button.types.d.ts
  src/types/Text.types.d.ts
  tests/components/atoms/Button.test.tsx
  tests/components/atoms/Text.test.tsx
  tests/jest.setup.cjs
  tsconfig.json
Labels: ci, styles
