Repository cognovi-ai/the-cdj-ui, pull requests merged in 2025-01, with the labels that each got.

#25 docs: initial docs
  docs/Components/default.md
  docs/README.md
  docusaurus/.gitignore
  docusaurus/README.md
  docusaurus/docusaurus.config.js
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/sidebars.js
  docusaurus/src/css/custom.css
  docusaurus/static/.nojekyll
  docusaurus/static/img/favicon.ico
  package-lock.json
  package.json
  scripts/typedoc/generate-docs.sh
  scripts/typedoc/plugins/custom-output.mjs
  src/app/page.tsx
  typedoc.json
Labels: documentation

#26 feat(api): implement API request utility and test suite
  src/hooks/apiRequest.ts
  tests/app/hooks/apiRequest.test.tsx
Labels: enhancement, api

#29 docs(generation): fix docs generation issue
  docs/app/(access)/account/page/functions/default.md
  docs/app/(access)/forgot-password/page/functions/default.md
  docs/app/(access)/login/page/functions/default.md
  docs/app/(access)/register/page/functions/default.md
  docs/app/(access)/reset-password/page/functions/default.md
  docs/app/(entry)/index/page/functions/default.md
  docs/app/layout/functions/default.md
  docs/app/not-found/functions/NotFoundContent.md
  docs/app/not-found/variables/default.md
  docs/app/page/functions/default.md
  docs/components/atoms/Button/functions/default.md
  docs/components/atoms/Checkbox/functions/default.md
  docs/components/atoms/Input/functions/default.md
  docs/components/atoms/Link/functions/default.md
  docs/components/atoms/Switch/functions/default.md
  docs/components/atoms/Text/functions/default.md
  docs/hooks/apiRequest/functions/apiRequest.md
  docs/hooks/apiRequest/interfaces/ApiOptions.md
  docs/theme/ThemeContext/functions/ThemeProvider.md
  docs/theme/ThemeContext/variables/ThemeContext.md
  docs/theme/theme/variables/darkTheme.md
  docs/theme/theme/variables/lightTheme.md
  docs/types/Button.types/functions/default.md
  docs/types/Button.types/interfaces/ButtonProps.md
  docs/types/Checkbox.types/functions/default.md
  docs/types/Checkbox.types/interfaces/CheckboxProps.md
  docs/types/Input.types/functions/default.md
  docs/types/Input.types/interfaces/InputProps.md
  docs/types/Link.types/functions/default.md
  docs/types/Link.types/interfaces/LinkProps.md
  docs/types/Switch.types/functions/default.md
  docs/types/Switch.types/interfaces/SwitchProps.md
  docs/types/Text.types/functions/default.md
  docs/types/Text.types/interfaces/TextProps.md
  docusaurus/docusaurus.config.js
  scripts/typedoc/generate-docs.sh
  scripts/typedoc/plugins/custom-output.mjs
  typedoc.json
Labels: documentation

#32 feat(access)!: add useAccess hook and accessApi layer with tests
  src/hooks/api/accessApi.ts
  src/hooks/apiRequest.ts
  src/hooks/useAccess.ts
  tests/hooks/api/accessApi.test.tsx
  tests/hooks/apiRequest.test.tsx
  tests/hooks/useAccess.test.tsx
Labels: enhancement, feature, api

#34 chore(eslint): update ESLint configuration to flat config
  eslint.config.js
  jest.config.js
  package-lock.json
  package.json
  src/hooks/api/accessApi.ts
  src/hooks/apiRequest.ts
  src/hooks/useAccess.ts
  tests/jest.setup.cjs
Labels: styles, version-update

#36 fix(button): add Roboto font family to button component
  src/theme/theme.ts
Labels: styles

#38 feat(journal): add provider pattern for journal context
  src/app/layout.tsx
  src/contexts/JournalContext.ts
  src/contexts/JournalProvider.tsx
  src/contexts/useJournal.ts
  tests/contexts/JournalContext.test.tsx
Labels: feature

#35 feat(entry)!: add `useEntry` hook and `entryApi` with tests
  package-lock.json
  package.json
  src/hooks/api/accessApi.ts
  src/hooks/api/entryApi.ts
  src/hooks/apiRequest.ts
  src/hooks/useAccess.ts
  src/hooks/useEntry.ts
  tests/hooks/api/entryApi.test.tsx
  tests/hooks/useEntry.test.tsx
Labels: feature, api

#39 refactor: update entry `endpoints` naming convention
  src/hooks/api/entryApi.ts
  tests/hooks/api/entryApi.test.tsx
Labels: patch, refactor
